name: webview_platform_interface
description: A common platform interface for the webview plugin.
repository: https://github.com/abandoft/webview_all
homepage: https://github.com/abandoft/webview_all
issue_tracker: https://github.com/abandoft/webview_all/issues
version: 1.4.4

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.7.0
  plugin_platform_interface: ^2.1.7

dev_dependencies:
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  mockito: ^5.4.4

topics:
  - webview
  - webview-flutter
  - platform-interface
  - browser
  - html
